version: '3.4'

# Services definition for local building & deployment

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}-app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app_prod
    # Deploy
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    volumes:
      - .:/app
      - /app/venv
      # - .:/home/app
      # - /home/app/venv # Does not work with non-root user
    # ports:
    #   # HTTP
    #   - target: 80
    #     published: ${HTTP_PORT:-80}
    #     protocol: tcp
