version: '3.4'

# Services overrides for running on ROCm GPU

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-stable-diffusion-webui-cuda}:${DOCKER_TAG:-latest}
    build:
      args:
        PYTHON_BASE: ${PYTHON_BASE:-rocm}
