version: '3.4'

# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-stable-diffusion-webui}:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app_dev
      args:
        PYTHON_BASE: ${PYTHON_BASE:-base} # Valid values: base, cuda, rocm
        PORT: ${EXPOSED_PORT:-80}
    # Deploy
    volumes:
      - .:/app
      - /app/venv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      # HTTP
      - target: ${EXPOSED_PORT:-80}
        published: ${HTTP_PORT:-80}
        protocol: tcp
